services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - ./notes:/usr/src/app/notes
   









