services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npx nodemon server.js --host 0.0.0.0 --port 3000 --cache ./cache

   









